### ISSUE TITLE
GraphQl playground not working after configuring plugin

### ISSUE THREAD

**Issue by karishmagolani01** [joas8211/payload-tenancy#30]

**Comment by karishmagolani01** [comment]
Nvm url for playground is /api/playground (src/plugin.ts) instead of default url as mentioned in docs (https://payloadcms.com/docs/graphql/overview) /api/graphql-playground

**Comment by joas8211** [comment]
The default GraphQL Playground route is now fixed with version v2.0.1. It's now correctly `/api/graphql-playground`. It was wrong due to me reading outdated / wrong code documentation from Payload. I'll opened an issue there to get the documentation (jsdoc comment) fixed: https://github.com/payloadcms/payload/issues/4037
